setx COLLECTOR_SERVER_ADDRESS "kubert.dmz.oktawave.com"
setx COLLECTOR_SERVER_PORT "9092"
setx COLLECTOR_TOPIC "test"

setx EMITTER_SERVER_ADDRESS "10.0.154.110"
setx EMITTER_SERVER_PORT "9200"
setx EMITTER_INDEX "test"
setx EMITTER_DOCUMENT "doc"
