apiVersion: v1
kind: Service
metadata:
  annotations:
    flowDef:
      priority: 5
      type: single
      base: /spec/collector
  name: collector
  labels:
    name: collector
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: collector
  sessionAffinity: None
  type: ClusterIP
