apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    flowDef:
      type: single
      base: /spec/collector
  name: collector
spec:
  replicas: ((cnt:int))
  template:
    metadata:
      labels:
        app: collector
    spec:
      nodeSelector:
        role: node
      securityContext:
        runAsUser: 501
        fsGroup: 501
      initContainers:
      - name: kafka-availability-check
        image: registry.hn.oktawave.com/busybox:1.29.2
        command: ['sh', '-c', 'while ! echo exit | nc -w1 kafka-service 9092; do sleep 4; done;']
      containers:
      - name: collector
        image: ((@ENV[COLLECTOR_IMAGE]))
        ports:
        - containerPort: 8080
          name: entry
        env:
        - name: LISTEN_PORT
          value: "8080"
        - name: CLIENT_ID
          value: "((/spec/clientId:name))"
        - name: TOKEN_HEADER
          value: "X-Token"
        - name: ID_SERVER_URL
          value: "((@ENV[ID_SERVER_URL]))"
        - name: KAFKA_BOOTSTRAP_SERVER
          value: "kafka-service:9092"
        - name: CONFIG_FILE
          value: "/etc/config/routing.yaml"
        - name: VERBOSE
          value: "((@ENV[VERBOSE_COLLECTOR]))"
        - name: SKIP_META
          value: "((@ENV[SKIP_META]))"
        - name: BACKDOOR_TOKEN
          value: "3133731337"
        - name: SARAMA_MAX_REQUEST_SIZE
          value: "10485760"
        volumeMounts:
        - name: routing
          mountPath: /etc/config
      volumes:
        - name: routing
          configMap:
            name: collector-routing
