apiVersion: v1
kind: Service
metadata:
  annotations:
    flowDef:
      priority: 5
      type: single
      base: /spec/elasticsearch
      condition: "*cnt"
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: http
    port: 9200
