apiVersion: v1
kind: Service
metadata:
  annotations:
    flowDef:
      priority: 5
      type: single
      base: /spec/emitter
  name: emiter
  labels:
    app: emiter
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: emiter
