apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    flowDef:
      type: single
      base: /spec/flink
      condition: "*cnt"
  name: flink-taskmanager
spec:
  replicas: ((cnt:int))
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      nodeSelector:
        role: node
      initContainers:
      - name: kafka-availability-check
        image: registry.hn.oktawave.com/busybox:1.29.2
        command: ['sh', '-c', 'while ! echo exit | nc -w1 kafka-service 9092; do sleep 4; done;']
      resources:
        limits:
          memory: ((limits/memory))
          cpu: ((limits/cpu))
      containers:
      - name: flink-taskmanager
        image: ((@ENV[FLINK_IMAGE]))
        args:
        - taskmanager
        ports:
        - containerPort: 6121
          name: data
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: "flink-jobmanager"
        - name: KAFKA_HOSTNAME
          value: "kafka-service" 
        - name: KAFKA_PORT
          value: "9092" 
        - name: KAFKA_GROUP_ID
          value: "test-consumer-group" 
        - name: ELASTICSEARCH_HOSTNAME
          value: "elasticsearch" 
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_PROTOCOL
          value: "http"
        - name: REDIS_HOSTNAME
          value: "redis-cluster"
        - name: REDIS_PORT
          value: "6379"
