apiVersion: v1
kind: Service
metadata:
  annotations:
    flowDef:
      priority: 5
  name: flow-api
  labels:
    app: flow-api
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: flow-api
