apiVersion: v1
kind: Service
metadata:
  annotations:
    flowDef:
      priority: 5
      type: single
      base: /spec/kafka
  name: kafka-service
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: server
  clusterIP: None
  selector:
    app: kafka
