apiVersion: v1
kind: Secret
metadata:
  annotations:
    flowDef:
      priority: 2
      type: list
      base: /spec/processor
      condition: "*credentials"
  name: processor-cred-((name:name))
  namespace: ((/spec/namespace))
data:
  .dockerconfigjson: ((credentials))
type: kubernetes.io/dockerconfigjson
