kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pvc-updater-((/spec/namespace))
rules:
- apiGroups: ["horizon.oktawave"]
  resources: ["flows"]
  resourceNames: ["((/spec/namespace))"]
  verbs: ["get"]
