apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvc-updater
  template:
    metadata:
      labels:
        app: pvc-updater
    spec:
      serviceAccountName: pvc-updater
      containers:
      - name: pvc-updater
        image: registry.hn.oktawave.com/pvc-updater:f4429e8d2e44228205c9ce32525788f853110f85
