apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis-cluster
  annotations:
    flowDef:
      priority: 5
      type: single
      base: /spec/redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: gossip
  clusterIP: None
  selector:
    app: redis-cluster
