apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster
  labels:
    app: redis-cluster
  annotations:
    flowDef:
      priority: 3
      type: single
      base: /spec/redis
data:
  fix-ip.sh: |
    #!/bin/sh
    CLUSTER_CONFIG="/data/nodes.conf"
    if [ -f ${CLUSTER_CONFIG} ]; then
      if [ -z "${POD_IP}" ]; then 
        echo "Unable to determine Pod IP address!"
        exit 1
      fi
      echo "Updating my IP to ${POD_IP} in ${CLUSTER_CONFIG}"
      sed -i.bak -e '/myself/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${POD_IP}/' ${CLUSTER_CONFIG}
    fi
    exec "$@"
  bootstrap.sh: |
    #!/bin/bash
    redis-server /conf/redis.conf &
    sleep 1
    if [ "$(hostname)" == "redis-cluster-5" ]; then
        if [ "$(grep -v myself /data/nodes.conf | wc -l)" -lt "2" ]; then
            echo yes | redis-cli --cluster create --cluster-replicas 1 $(for i in `seq 0 5`; do echo "$(getent hosts redis-cluster-${i}.redis.((/spec/namespace)).svc.cluster.local | awk '{print $1}'):6379"; done | xargs)
        fi
    fi
    wait
  redis.conf: |+
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1
    appendonly yes
    protected-mode no
