apiVersion: v1
kind: Service
metadata:
  annotations:
    flowDef:
      priority: 5
      type: single
      base: /spec/kafka
  name: zk-svc
  labels:
    app: zk-svc
spec:
  clusterIP: None
  ports:
  - port: 2181
    name: client
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  publishNotReadyAddresses: true
  selector:
    app: zk
